export default [
   { name: 'Craft Supplies & Tools', param: 'craft-supplies-and-tools' },
   { name: 'Home & Hobby', param: 'home-and-hobby' },
   { name: 'Woodworking & Carpentry', param: 'woodworking-and-carpentry' },
   { name: 'Electronics & Circuitry', param: 'electronics-and-circuitry' },
   { name: 'Food & Fermenting', param: 'food-and-fermenting' },
   { name: 'Jewellery & Beauty', param: 'jewellery-and-beauty' },
   { name: 'Beads', param: 'beads' },
   { name: 'Charms', params: 'charms' },
   { name: 'Pendants', params: 'pendants' },
   { name: 'Sewing & Fiber', param: 'sewing-and-fiber' },
   { name: 'Knitting', param: 'knitting' },
   { name: 'Sewing', param: 'sewing' },
   { name: 'Cross Stitch', param: 'cross-stitch' },
   { name: 'Papercraft', param: 'papercraft' },
   { name: 'Scrapbooking', param: 'scrapbooking' },
   { name: 'Stamping', param: 'stamping' },
   { name: 'Origami', param: 'origami' },
   { name: 'Visual Arts', param: 'visual-arts' },
   { name: 'Painting', param: 'painting' },
   { name: 'Printing & Printmaking', param: 'printing-and-printmaking' },
   { name: 'Photography', param: 'photography' },
   { name: 'Calligraphy & Pens', param: 'calligraphy-and-pens' },
   { name: 'Sculpting & Forming', param: 'sculpting-and-forming' },
   { name: 'Ceramics & Pottery', param: 'ceramics-and-pottery' },
   { name: 'Metalworking', param: 'metalworking' },
   { name: 'Carving & Whittling', param: 'carving-and-whittling' },
   { name: 'Jewellery & Accessories', param: 'jewellery-and-accessories' },
   { name: 'Accessories', param: 'accessories' },
   { name: 'Hats & Caps', param: 'hats-and-caps' },
   { name: 'Hair Accessories', param: 'hair-accessories' },
   { name: 'Sunglasses & Eyewear', param: 'sunglasses-and-eyewear' },
   { name: 'Belts & Braces', param: 'belts-and-braces' },
   { name: 'Bags & Purses', param: 'bags-and-purses' },
   { name: 'Backpacks', param: 'backpacks' },
   { name: 'Handbags', param: 'handbags' },
   { name: 'Phone Cases', param: 'phone-cases' },
   { name: 'Necklaces', param: 'necklaces' },
   { name: 'Pendants', param: 'pendants' },
   { name: 'Crystal Necklaces', param: 'crystal-necklaces' },
   { name: 'Chains', param: 'chains' },
   { name: 'Rings', param: 'rings' },
   { name: 'Stackable Rings', param: 'stackable-rings' },
   { name: 'Bands', param: 'band' },
   { name: 'Engagement Rings', param: 'engagement-rings' },
   { name: 'Earrings', param: 'earrings' },
   { name: 'Stud Earrings', param: 'stud-earrings' },
   { name: 'Chandelier Earrings', param: 'chandelier-earrings' },
   { name: 'Clip on Earrings', param: 'clip-on-earrings' },
   { name: 'Bracelets', param: 'bracelets' },
   { name: 'Bangles', param: 'bangles' },
   { name: 'Cuff Bracelets', param: 'cuff-bracelets' },
   { name: 'Clothing & Shoes', param: 'clothing-and-shoes' },
   { name: "WOMEN'S", param: 'womens' },
   { name: 'Dresses', param: 'women-dresses' },
   { name: 'Tops & Tees', param: 'women-tops-and-tees' },
   { name: 'Skirts', param: 'women-skirts' },
   { name: 'Trousers', param: 'women-trousers' },
   { name: 'Jumpers', param: 'women-jumpers' },
   { name: 'Swimwear', param: 'women-swimwear' },
   { name: 'Boots', param: 'women-boots' },
   { name: "MEN'S", param: 'mens' },
   { name: 'Shirts', param: 'men-shirts' },
   { name: 'Jumpers', param: 'men-jumpers' },
   { name: 'Boots', param: 'men-boots' },
   { name: "KIDS' & BABY", param: 'kids-and-baby' },
   { name: 'Home & Living', param: 'home-and-living' },
   { name: 'Home', param: 'home' },
   { name: 'Decorative Cushions', param: 'decorative-cushions' },
   { name: 'Candles & Holders', param: 'candles-and-holders' },
   { name: 'Clocks', param: 'clocks' },
   { name: 'Rugs', param: 'rugs' },
   { name: 'Furniture', param: 'furniture' },
   { name: 'Bathroom', param: 'bathroom' },
   { name: 'Storage & Organisation', param: 'storage-and-organisation' },
   { name: 'Office', param: 'office' },
   { name: 'Lighting', param: 'lighting' },
   { name: 'Food & Drink', param: 'food-and-drink' },
   { name: 'Bath & Beauty', param: 'bath-and-beauty' },
   { name: 'Bath Accessories', param: 'bath-accessories' },
   { name: 'Makeup & Cosmetics', param: 'makeup-and-cosmetics' },
   { name: 'Skin Care', param: 'skin-care' },
   { name: 'Essential Oils', param: 'essential-oils' },
   { name: 'Fragrances', param: 'fragrances' },
   { name: 'Bath Bombs', param: 'bath-bombs' },
   { name: 'Pet Supplies', param: 'pet-supplies' },
   { name: 'Pet Collars & Leashes', param: 'pet-collars-and-leashes' },
   { name: 'Pet Furniture', param: 'pet-furniture' },
   { name: 'Pet Clothing & Shoes', param: 'pet-clothing-and-shoes' },
   { name: 'Pet Carriers & Houses', param: 'pet-carriers-and-houses' },
   { name: 'Wedding & Party', param: 'wedding-and-party' },
   { name: 'Party Supplies', param: 'party-supplies' },
   { name: 'Party Decor', param: 'party-decor' },
   { name: 'Baking & Cake Decoration', param: 'baking-and-cake-decoration' },
   { name: 'Invitation & Paper', param: 'invitation-and-paper' },
   { name: 'Wedding Invitation Kits', param: 'wedding-invitation-kits' },
   { name: 'Stationery', param: 'wedding-stationery' },
   { name: 'Greeting Cards', param: 'greeting-cards' },
   { name: 'Gift Wrapping', param: 'gift-wrapping' },
   { name: 'Wedding Gifts', param: 'wedding-gifts' },
   { name: 'Wedding Favours', param: 'wedding-favours' },
   { name: 'Guest Books', param: 'guest-books' },
   { name: 'Album & Scrapbooks', param: 'album-and-scrapbooks' },
   { name: 'Wedding Clothing', param: 'wedding-clothing' },
   { name: 'Bridal Gowns', param: 'bridal-gowns' },
   { name: 'Flower Girl Dresses', param: 'flower-girl-dresses' },
   { name: 'Suits', param: 'suits' },
   { name: 'Bridesmaid Dresses', param: 'bridesmaid-dresses' },
   { name: 'Toys & Entertainment', param: 'toys-and-entertainment' },
   { name: 'Toys', param: 'toys' },
   { name: 'Stuffed Animals', param: 'stuffed-animals' },
   { name: 'Games & Puzzles', param: 'games-and-puzzles' },
   { name: 'Learning & School', param: 'learning-and-school' },
   { name: 'Slime & Foam', param: 'slime-and-foam' },
   { name: 'Electronics & Accessories', param: 'electronics-and-accessories' },
   { name: 'Cell Phone Accessories', param: 'cell-phone-accessories' },
   { name: 'Gadgets', param: 'gadgets' },
   { name: 'Video Games', param: 'video-games' },
   { name: 'Cameras', param: 'cameras' },
   { name: 'Computers & Peripherals', param: 'computers-and-peripherals' },
   { name: 'Books', param: 'books' },
   { name: 'Blank Books', param: 'blank-books' },
   { name: 'Calendar & Planners', param: 'calendar-and-planners' },
   { name: 'Comics & Graphic Novels', param: 'comics-and-graphic-novels' },
   { name: 'Literature & Fiction', param: 'literature-and-fiction' },
   { name: 'Poetry', param: 'poetry' },
   { name: 'Guides & How Tos', param: 'guides-and-how-tos' },
   { name: 'Zines & Magazines', param: 'zines-and-magazines' },
   { name: 'Movies & Music', param: 'movies-and-music' },
   { name: 'Musical Instruments', param: 'musical-instruments' },
   { name: 'Recorded Audio', param: 'recorded-audio' },
   { name: 'Sheet Music', param: 'sheet-music' },
   { name: 'All Movies', param: 'all-movies' },
   { name: 'All Music', param: 'all-music' },
   { name: 'Art & Collectibles', param: 'art-and-collectibles' },
   { name: 'Prints', param: 'prints' },
   { name: 'Photography', param: 'photography' },
   { name: 'Painting', param: 'painting' },
   { name: 'Sculpture', param: 'sculpture' },
   { name: 'Glass Art', param: 'glass-art' },
   { name: 'Drawing & Illustration', param: 'drawing-and-illustration' },
   { name: 'Mixed Media', param: 'mixed-media' },
   { name: 'Fibre Arts', param: 'fibre-arts' },
   { name: 'Dolls & Miniatures', param: 'dolls-and-miniatures' },
   { name: 'Collectibles', param: 'collectibles' },
   { name: 'Figurines', param: 'figurines' },
   { name: 'Vintage', param: 'vintage' }
];
